apiVersion: v1
kind: Pod
metadata:
  name: fastapi-ml
  labels:
    app: fastapi-ml
spec:
  containers:
    - image: arhimisha/ml_in_prod_task_2:v1
      name: fastapi-ml
      ports:
        - containerPort: 80
