version: 1
formatters:
  simple:
    class: logging.Formatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  full_file_handler:
    class: logging.FileHandler
    filename: heart_ml_project.log
    level: DEBUG
    formatter: simple
  info_stream_handler:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
loggers:
  heart_ml_project:
    level: DEBUG
    handlers: [full_file_handler]
    propagate: yes
root:
  level: DEBUG
  handlers: [info_stream_handler]