DEFAULT_LOGGING_CONFIG_PATH = './configs/logging_config.yml'
APPLICATION_NAME = 'heart_ml_project'
DEFAULT_CONFIG_PATH = './configs/train_config_lr.yml'
DEFAULT_DATASET_PATH = './data/raw/heart.csv'
DEFAULT_OUTPUT_PATH = './data/prediction.csv'
